name: Run Python UnitTests

on:
  push:
    branches: [main, 'beta/*', 'alpha/*']
  pull_request:
    branches: [main, 'beta/*', 'alpha/*']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install integration dependencies
        run: |
          pip install $(jq -r '.requirements[]' custom_components/abbfreeathome_ci/manifest.json)

      - name: Install development dependencies
        run: |
          pip install -r dev-requirements.txt

      - name: Test with pytest
        run: |
          pytest \
            --cov=. \
            --cov-branch \
            --cov-report=xml:coverage/coverage.xml \
            --junitxml=junit/test-results.xml

      - name: Code Coverage Summary Report
        id: coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/coverage.xml
          badge: true
          format: markdown
          output: both
          fail_below_min: true
          thresholds: '100 100'

      - name: Write Coverage to Job Summary
        if: success() || steps.coverage.conclusion == 'failure'
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6.0.1
        if: success() || failure()
        with:
          report_paths: junit/test-results.xml
          detailed_summary: true
          comment: false
